
<navbar:define name="panoramas">

           <navbar:header>
             <ul>
           </navbar:header>
	   
           <navbar:prolog>
	     <li>
	   </navbar:prolog>

           <navbar:button id=panoramas_krefeld  url="$(PANORAMAS)/krefeld.html"  txt="Krefeld">
           <navbar:button id=panoramas_salzburg url="$(PANORAMAS)/salzburg.html" txt="Salzburg">
           <navbar:button txt="Second bar item">

           <navbar:footer>
             </ul>
           </navbar:footer>
</navbar:define>


