<center>
  [ <href url="$(ROOT)/"      target="_parent" name="<en: Home><de: Startseite>"> ::
    <href url="$(PANORAMAS)"  target="_parent" name="<en: Panoramas><de: Panoramen>"> ::
    <href url="$(OBJECTS)/"   target="_parent" name="<en: Objects><de: Objekte>"> ::
    <href url="$(TUTORIAL)/"  target="_parent" name="<en: Tutorial><de: Tutorial>"> ::
    <href url="$(EQUIPMENT)/" target="_parent" name="<en: Equipment><de: Ausrüstung>"> ::
    <href url="$(DOWNLOADS)/" target="_parent" name="<en: Downloads><de: Downloads>"> ::
    <href url="$(CONTACT)/"   target="_parent" name="<en: Contact><de: Kontakt>"> ]


<br>
<br><small>
   &copy; 2002-2015 <href url="mailto:Peter%20Reimer%20%3Cpeter%404pi.org%3E" name="Peter Reimer"><br>
   <en: last modified><de: letzte Änderung>: $(WML_SRC_ISOTIME)
	</small>		 
</center>

