<table cellpadding="0" cellspacing="0" border="0" width="100%" height="25">
<tr>
  <td class="footer" align="left" valign="middle" width="175" height="25">
  <p class="footer">&copy; 2002 <href url="$(CONTACT)" name="<font color="#cccccc">Peter Reimer</font>"><br>
#  &copy; 2002 <href url="$(CONTACT)" image="$(IMG)/sig_small.gif" alt="Peter Reimer"><br>
  </td>
  
  <td class="footer" valign="middle" ><center>
  [ <href url="$(ROOT)"      target="_parent" name="<font color="#cccccc">Home</font>"> ::
    <href url="$(PANORAMAS)" target="_parent" name="<font color="#cccccc">Panoramas</font>"> ::
    <href url="$(OBJECTS)"   target="_parent" name="<font color="#cccccc">Objects</font>"> ::
    <href url="$(TUTORIAL)"  target="_parent" name="<font color="#cccccc">Tutorial</font>"> ::
    <href url="$(EQUIPMENT)" target="_parent" name="<font color="#cccccc">Equipment</font>"> ::
    <href url="$(DOWNLOADS)" target="_parent" name="<font color="#cccccc">Downloads</font>"> ::
    <href url="$(LINKS)"     target="_parent" name="<font color="#cccccc">Links</font>"> ::
    <href url="$(CONTACT)"   target="_parent" name="<font color="#cccccc">Contact</font>"> ]</center>
  </td>
</tr>
</table>       
