 txt="
 ####################################
 ##########  L A T E S T  ###########
 ####################################
 <p class="subnavHeader"><en: Latest Panorama><de: Letztes Panorama></p>
 ##
 <p class="subnav">
 <em class="date">2004-11-7</em>
 <a href="$(PANORAMAS)/koeln.<de: de><en: en>.html" class="nav-n">
 <en: Henry Cartier Bresson Exibition>
 <de: Henry Cartier Bresson Ausstellung>
 </a>
 <href url="$(PANORAMAS)/koeln.<de: de><en: en>.html" image=$(PANORAMAS)/thumbs/hcb2.jpg>
 <br>
 <br>
 ####################################
 "

