 txt="
 ####################################
 ##########  N E W S  ###############
 ####################################
 <p class="subnavHeader"><en: News><de: Neues></p>
 <p class="subnav">
 <em class="date">2003-04-18</em><href name="
 <en: making guided tours with PTViewer>
 <de: geführte Touren mit PTViewer>" url="$(TUTORIAL)/guided.html">
 <p style="text-align:right" class="subnav">
 <href url="$(ROOT)/logbook" name="<en: older news><de: ältere Neuigkeiten> &raquo;">
 ####################################
 "

