##
## javascript für rollovers
##

<define-tag rollover_submenu >
 onMouseOver="highlight_sub(this)" onMouseDown="highlight_sub(this)" onMouseUp="normalwhite_sub(this)" onMouseOut="normalwhite_sub(this)"
 </define-tag>
							   
<define-tag rollover_mainmenu >
 onMouseOver="highlight_main(this)" onMouseDown="highlight_main(this)" onMouseUp="normalwhite_main(this)" onMouseOut="normalwhite_main(this)"
</define-tag>
